### ISSUE TITLE
Keybind to copy the ID

### ISSUE THREAD

**Issue by ajrc0re** [silverwind/idTip#103]
For example, SHIFT+CTRL+Right click on a buff/debuff/etc will copy the spell ID to your clipboard. Would make things like creating aura filters in shadowed unit frames infinitely easier

**Comment by silverwind** [comment]
The module does not interact with the origin of the tooltip at all, so such modifier clicks are not possible. Also I think even if we somehow obtain a reference to these buttons, it's likely not possible to modify them because of taint.

What might be possible is to allow moving the mouse into the tooltip when a modifier is pressed, and this could maybe allow text selection in the tooltip. But overall I have doubts that this is possible with Blizzard's APIs.
