### ISSUE TITLE
SetRecipeResultItem is not a function ...

### ISSUE THREAD

**Issue by rbpaiett** [silverwind/idTip#78]
I get this in the TBC version upon launch of the LK pre-patch:

6x idTip\idTip-9.0.2-bcc.lua:141: hooksecurefunc(): SetRecipeResultItem is not a function
[string "=[C]"]: in function `hooksecurefunc'
[string "@idTip\idTip-9.0.2-bcc.lua"]:141: in main chunk

**Comment by ItsJustMeChris** [comment]
Long time.. but worth a try I guess..

Are you using the code from curse or directly downloaded from GitHub? Not sure this would be an issue from the version on GitHub currently, but I can take a look in a bit..

**Comment by rbpaiett** [comment]
Thanks!

**Comment by rbpaiett** [comment]
I'm using the one from Curse.

**Comment by ItsJustMeChris** [comment]
Okay, until silverwind decides to update the hosted addons or I decide to make a proper community fork, you'll have to download the addon from GitHub, https://github.com/silverwind/idTip/archive/refs/heads/master.zip just unzip contents to a folder named "idTip" INSTEAD of what github will provide ("idTip-master") and place it into your wow addons directory

**Comment by rbpaiett** [comment]
Super, thanks a lot!

**Comment by silverwind** [comment]
Should be fixed since a while now
