### ISSUE TITLE
Profession Spells

### ISSUE THREAD

**Issue by silverwind** [silverwind/idTip#8]
Posted by lucidentrophy on curse:

> I have one request : could you have it show the spell ids on profession skills? I want to use this mod in coordination with /run PickupSpell(spellidhere) for putting daily profession cooldowns on my action bar.
> 
> Examples of some spells that I'd like to see : 
> 
> http://www.wowhead.com/spells=11?filter=cr=25:9;crs=3:9;crv=10:0
> 
> and
> 
> http://www.wowhead.com/spells=11?filter=na=secrets of;cr=16;crs=6;crv=0
> 
> Thanks!

**Comment by silverwind** [comment]
Will look into it. If these are really tooltips, I'm gonna find and add their ID.

**Comment by Lucidentropy** [comment]
Sorry I didn't followup sooner - I realized that these don't actually show up in game - the profession ui doesn't have a popup when you hover over the skill to make these items. That means the solution would be to either 1. Find a way to force tooltips for profession spells or 2. Put the spell ids on the parent spells (since this technically changes the addon, this probably needs to be a separate addon)

**Comment by silverwind** [comment]
I could force tooltips like I do in the achievement window, but I'd rather avoid doing that as it can be intrusive to suddenly having tooltips pop up. This addon should be tooltip-focused only.
