### ISSUE TITLE
Add spell tooltip to EncounterJournal

### ISSUE THREAD

**Issue by mrbuds** [silverwind/idTip#99]
I made a micro addon to add tooltips to EncounterJournal, I'm not sure if this feature fit the scope of idTip, but feel free to use it if you want

![image](https://github.com/silverwind/idTip/assets/189656/5831fe23-fa08-4079-a6a8-ddfcdda92828)

[EncounterJournalTooltips.zip](https://github.com/silverwind/idTip/files/12640750/EncounterJournalTooltips.zip)

**Comment by silverwind** [comment]
Yeah I will add that as well as it fits the theme.

**Comment by silverwind** [comment]
I'll pass on this one because [your addon](https://www.curseforge.com/wow/addons/encounterjournal-spell-info) now also creates the spell tooltip and tooltip creation is generally out of scope for this addon.

Also, thanks for adding compatibility check. I do think I will alter the text from "SpellID" to your "Spell ID" sometimes.
